TRUNCATE TABLE config;
INSERT INTO config (name, value) VALUES
('sample', '{"status": 1, "variable": 1, "thread": 1, "object": 1, "seconds": 5, "count": 5}');

TRUNCATE TABLE help;
INSERT INTO help (msg) VALUES
('DoiT StatPack for MySQL'),
(''),
('This database only deployment enables the ability to collect summarized'),
('information of a MySQL (AWS or GCP) instances including variables, status,'),
('schema, and processes in a consistent reproducible way.'),
(''),
('Several database helpers enable a quick analysis before leveraging other'),
('tools to delve into more information.'),
(''),
('#Help'),
('Refer to the installation README for setup of StatPack for MySQL.'),
(''),
('To reset all data to the system defaults use `statpack_truncate`'),
(''),
('    call statpack_truncate();'),
(''),
('To collect a short sample to validate your setup use `statpack_sample`.'),
('It is recommended you use the previous function to clear the sample before'),
('detailed monitoring.'),
(''),
('    call statpack_sample();'),
(''),
('The available statistics at this time are.'),
(''),
('- `variable` - This collects information on the global variables'),
('- `status`  - This collects information on the global status'),
('- `thread` - This collects information on the running threads'),
('- `object` - This collects information on the size and volume of your objects'),
(''),
('To collect one sample of statistics use `statpack_gather`.'),
(''),
('    set @stats:= ''{"status": 1, "variable": 1, "thread": 1, "object": 1}'';'),
('    call statpack_gather(@stats);'),
(''),
('All types of statistics are optional, if you do not wish to collect them'),
('you can either set to false (0) or not specify.'),
(''),
('    set @stats := ''{"status": 1, "thread": 1}'';'),
('    call statpack_gather(@stats);'),
(''),
('If you wish to wait a certain number of seconds before collecting the'),
('statistics use `statpack_wait`'),
(''),
('    set @stats := ''{"status": 1, "thread": 1}'';'),
('    set @wait := 60;'),
('    call statpack_wait(@wait, @stats);'),
(''),
('To collect a set of statistics over a period of time with regular intervals'),
('use `statpack_iterate`'),
(''),
('    # Collect 4 samples every 15 seconds for the given stats'),
('    set @stats := ''{"status": 1, "thread": 1}'';'),
('    set @cnt := 4;'),
('    set @wait := 15;'),
('    call statpack_iterate(@cnt, @wait, @stats);'),
(''),
('To get a summary of the change of status for a given attribute for'),
('all sample times.'),
(''),
('    call status_change("Questions");'),
(''),
('This will produce the following output which provides the change of the'),
('given status (both the time and value).  Using the prior example of'),
('executing 4 samples every 15 seconds, we see that the change in the value'),
('from the first execution to the last execution.'),
(''),
('NOTE: Some MySQL status values are not incremental so this does not function'),
('as expected.'),
(''),
('    +---------------------+-----------+---------+--------------+'),
('    | created             | name      | seconds | value_change |'),
('    +---------------------+-----------+---------+--------------+'),
('    | 2022-12-15 14:20:23 | Questions |       0 |            0 |'),
('    | 2022-12-15 14:20:38 | Questions |      15 |          118 |'),
('    | 2022-12-15 14:20:53 | Questions |      15 |          105 |'),
('    | 2022-12-15 14:21:08 | Questions |      15 |          105 |'),
('    +---------------------+-----------+---------+--------------+'),
(''),
('Some other examples include:'),
(''),
('    call status_change("Innodb_rows_inserted");'),
('    call status_change("Innodb_data_fsyncs");'),
('    call status_change("Innodb_buffer_pool_write_requests");')
;
